### ISSUE TITLE
Could not find the implementation for builder after updating to Angular 8

### ISSUE THREAD

**Issue by heavybeard** [alan-agius4/speedy-build-angular#25]
After updating to Angular 8 I get this error with the custom runner. I think you only have to update the `@angular-devkit/core` package to 8 version.

```
Could not find the implementation for builder @speedy/build-angular:stylelint
Error: Could not find the implementation for builder @speedy/build-angular:stylelint
  at WorkspaceNodeModulesArchitectHost.resolveBuilder (/application-root/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:49:19)
  at RunCommand.runSingleTarget (/application-root/node_modules/@angular/cli/models/architect-command.js:176:55)
  at async RunCommand.runArchitectTarget (/application-root/node_modules/@angular/cli/models/architect-command.js:216:24)
```

Maybe you just work on it with this PR https://github.com/alan-agius4/speedy-build-angular/pull/24

**Comment by alan-agius4** [comment]
Hi, the architect API changed and didn’t have time yet to fix it.

Will try to do it in the next couple of days. Sorry for the inconvenience.

**Comment by heavybeard** [comment]
Many thanks for your work 🎉
